// <auto-generated />
using System;
using MessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int?>("BreakfastDishPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("BreakfastVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BreakfastVerifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DinnerDishPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("DinnerVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DinnerVerifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DishPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBreakfastPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDinnerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLunchPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int?>("LunchDishPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("LunchVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LunchVerifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("VerifiedByUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceId");

                    b.HasIndex("BreakfastDishPlanId");

                    b.HasIndex("DinnerDishPlanId");

                    b.HasIndex("DishPlanId");

                    b.HasIndex("LunchDishPlanId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.DishPlan", b =>
                {
                    b.Property<int>("DishPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishPlanId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishPlanId");

                    b.ToTable("DishPlan", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.MessPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixedWaterCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TeaPricePerCup")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PeriodId");

                    b.ToTable("MessPeriod", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.TeaEntry", b =>
                {
                    b.Property<int>("TeaEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeaEntryId"));

                    b.Property<int>("Cups")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("VerifiedByUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TeaEntryId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("TeaEntry", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.TeaRecord", b =>
                {
                    b.Property<int>("TeaRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeaRecordId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalCupsServed")
                        .HasColumnType("int");

                    b.HasKey("TeaRecordId");

                    b.HasIndex("PeriodId");

                    b.ToTable("TeaRecord", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.HasOne("MessManagement.Models.DishPlan", "BreakfastDishPlan")
                        .WithMany()
                        .HasForeignKey("BreakfastDishPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.DishPlan", "DinnerDishPlan")
                        .WithMany()
                        .HasForeignKey("DinnerDishPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.DishPlan", "DishPlan")
                        .WithMany("Attendances")
                        .HasForeignKey("DishPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessManagement.Models.DishPlan", "LunchDishPlan")
                        .WithMany()
                        .HasForeignKey("LunchDishPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.MessPeriod", "MessPeriod")
                        .WithMany("Attendances")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BreakfastDishPlan");

                    b.Navigation("DinnerDishPlan");

                    b.Navigation("DishPlan");

                    b.Navigation("LunchDishPlan");

                    b.Navigation("MessPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.HasOne("MessManagement.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.Attendance", "Attendance")
                        .WithMany("Payments")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessManagement.Models.MessPeriod", "MessPeriod")
                        .WithMany("Payments")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Attendance");

                    b.Navigation("MessPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.TeaEntry", b =>
                {
                    b.HasOne("MessManagement.Models.MessPeriod", "MessPeriod")
                        .WithMany("TeaEntries")
                        .HasForeignKey("PeriodId");

                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany("TeaEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MessPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.TeaRecord", b =>
                {
                    b.HasOne("MessManagement.Models.MessPeriod", "MessPeriod")
                        .WithMany("TeaRecords")
                        .HasForeignKey("PeriodId");

                    b.Navigation("MessPeriod");
                });

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MessManagement.Models.DishPlan", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("MessManagement.Models.MessPeriod", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("TeaEntries");

                    b.Navigation("TeaRecords");
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("TeaEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
